name: zustand
description: "Brings zustand's bear necessities for state management to Dart"
version: 0.0.5
repository: https://github.com/josiahsrc/flutter_zustand/tree/main/packages/zustand
homepage: https://github.com/josiahsrc/flutter_zustand/tree/main/packages/zustand

environment:
  sdk: ^3.3.1

dependencies:
  meta: ^1.11.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
